CrashingBlocks: 
   MaxSpeed: 3.0
   MinSpeed: 0.5
   ExplosionColours: 
   - 220,20,0
   - 20,0,220
   - 0,20,220
   - 220,22,202
   AudioPlayerIP: 192.168.1.101
   Balls: 2
   BallColour: 255,160,0
   AudioPlayerPort: 53000
   BackgroundSound: rise0
AudioPlayer: 
   Port: 53000
   Files: 
   - ambient-background,1
   - flutter-1
   - flutter-2
   - flutter-3
   - flutter-4
   - flutter-5
   - flutter-out
   - rise0,1
NeoPixelGUI: 
   Spacer: 5
   CustomLayout: none
   LedSize: 5
NeoPixelBoard: 
   RowsFirst: true
   LoopBack: false
Butterflies: 
   FlutterInSound: flute-flutter-in
   AudioPlayerIP: 192.168.1.101
   AudioPlayerPort: 53000
   BackgroundSound: ambient-background
   FlutterOutSound: flute-flutter-out
RainAnimation: 
   MinSize: 1
   MaxSpeed: 5
   MinSpeed: 2
   DropletCount: 200
   MaxSize: 3
LightBoardGUI: 
   OnlyOnOff: true
   LedSize: 2
   RefreshInterval: 60
   Spacing: 0
   OnlyRedGreen: true
Services: 
   MidiDevice: USB Uno MIDI Interface
PixelTape: 
   TapeRefresh: 1
SerialDmx: 
   Port: /dev/ttyUSB0
General: 
   ScenariosDirectory: scenarios
   Refresh: 50
   TriggerPackage: net.amarantha.gpiomofo.trigger
   PinScanInterval: 10
   TargetPackage: net.amarantha.gpiomofo.target
   HttpAsyncTargets: true
   ScenarioPackage: net.amarantha.gpiomofo.scenario
   Scenario: MessageBoard
LightSurface: 
   LayerCount: 10
   BoardClass: net.amarantha.gpiomofo.display.lightboard.LightBoardGUI
   Height: 64
   Width: 256
Gingerline: 
   LightingServerIP: 192.168.42.100
   C5-Amber: 255,80,0
   C0-BackgroundColour: 255,105,25
   LightingServerOscPort: 7700
   C3-Colour: 65,255,0
   C5-Green: 10,255,10
   PanicIP: 192.168.42.105
   MediaServerOscPort: 53000
   PanicPort: 8001
   ButtonHoldTime: 100
   C0-Colour3: 255,40,0
   C0-Colour2: 255,40,0
   C0-Colour1: 255,10,0
   C5-Blue: 40,40,255
   C0-Colour4: 255,10,0
   MediaServerIP: 192.168.42.99
   C5-Purple: 210,50,200
Gui: 
   Window-Output-GPIO: 191.0,139.0
   Window-Range-Sensor: 139.0,289.0
   Window-LightBoard: 140.0,433.0
   Window-NeoPixel: 146.0,351.0
   LogoFile: /home/grimalkin/code/gpiomofo/gpiomofo-logo.png
   Window-Input-GPIO: 130.0,166.0
   Window-GpioMofo: -3502.0,74.0
Aws: 
   ClientId: sdk-java
   CertificateFile: /home/grimalkin/Downloads/aws/SnootBox.cert.pem
   PrivateKeyFile: /home/grimalkin/Downloads/aws/SnootBox.private.key
   ClientEndpoint: a2q2k2ttlfw6v7.iot.us-west-2.amazonaws.com
