LightBoardGUI: 
   OnlyOnOff: true
   LedSize: 2
   RefreshInterval: 60
   Spacing: 0
   OnlyRedGreen: true
Services: 
   MidiDevice: USB Uno MIDI Interface
CrashingBlocks: 
   MedOSC: 192.168.1.101:53000/med|255
   MaxSpeed: 3.0
   HighOSC: 192.168.1.101:53000/high|255
   MinSpeed: 0.5
   ExplosionColours: 
   - 220,20,0
   - 20,0,220
   - 0,20,220
   - 0,220,20
   LowOSC: 192.168.1.101:53000/low|255
   CrashOSC: 192.168.1.101:53000/crash|255
   Balls: 2
   BallColour: 255,200,0
PixelTape: 
   TapeRefresh: 10
AudioPlayer: 
   Port: 53000
   Files: 
   - ambient-background
   - flute-flutter-in
   - flute-flutter-out
General: 
   ScenariosDirectory: scenarios
   Refresh: 50
   TriggerPackage: net.amarantha.gpiomofo.trigger
   PinScanInterval: 10
   TargetPackage: net.amarantha.gpiomofo.target
   HttpAsyncTargets: true
   ScenarioPackage: net.amarantha.gpiomofo.scenario
   Scenario: MessageBoard
LightSurface: 
   LayerCount: 10
   BoardClass: net.amarantha.gpiomofo.display.lightboard.LightBoardGUI
   Height: 32
   Width: 192
Gingerline: 
   LightingServerIP: 192.168.42.100
   C5-Amber: 255,80,0
   C0-BackgroundColour: 255,105,25
   LightingServerOscPort: 7700
   C3-Colour: 65,255,0
   C5-Green: 10,255,10
   PanicIP: 192.168.42.105
   MediaServerOscPort: 53000
   PanicPort: 8001
   ButtonHoldTime: 100
   C0-Colour3: 255,40,0
   C0-Colour2: 255,40,0
   C0-Colour1: 255,10,0
   C5-Blue: 40,40,255
   C0-Colour4: 255,10,0
   MediaServerIP: 192.168.42.99
   C5-Purple: 210,50,200
Gui: 
   Window-Output-GPIO: 20.0,20.0
   Window-Range-Sensor: 139.0,289.0
   Window-LightBoard: 0.0,212.0
   Window-NeoPixel: 1751.0,354.0
   LogoFile: /home/grimalkin/code/gpiomofo/gpiomofo-logo.png
   Window-Input-GPIO: 61.0,46.0
   Window-GpioMofo: 828.0,565.0
NeoPixelGUI: 
   Spacer: 0
   LedSize: 2
NeoPixelBoard: 
   RowsFirst: true
   LoopBack: false
Butterflies: 
   FlutterInSound: flute-flutter-in
   AudioPlayerIP: 192.168.1.101
   AudioPlayerPort: 53000
   BackgroundSound: ambient-background
   FlutterOutSound: flute-flutter-out
